name: test-github-packages-deploy

on:
  schedule:
    - cron: 0 2 * * *

  pull_request: []

jobs:
  test-action:
    if: github.event.pull_request.head.repo.full_name == 'oras-project/oras-py'
    name: Test Github Packages Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Environment
        run: conda create --quiet --name oras requests

      - name: Install Oras Python
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate oras
          pip install -e .

      - name: Test GitHub Packages Push/Pull
        env:
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          uri: ghcr.io/oras-project/oras-py/oras-py-test:latest
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate oras
          python setup.py sdist
          artifact=$(ls dist/*.tar.gz)
          echo ${token} | oras-py login -u ${user} ghcr.io --password-stdin
          echo "Preparing to push ${artifact} to ${uri}"
          oras-py push --debug ${uri} ${artifact}
          echo "Preparing to pull ${artifact}"
          oras-py pull --debug -a ${uri}
          ls
